Repository hyochan/hyo-gpt, pull requests merged in 2024-04, with the labels that each got.

#2 Improve chat history management and language responsiveness
  app/api/chat/route.ts
  bun.lockb
  package.json
  src/utils/common.ts
Labels: enhancement

#3 ci: add code review gpt
  .github/workflows/code_review.yml
Labels: ci

#4 chore(patch): remove polite words in kor
  .github/workflows/code_review.yml
  app/api/chat/route.ts
Labels: patch

#5 feat: enh prompt for better conversation
  app/api/chat/route.ts
Labels: enhancement
